### ISSUE TITLE
Define usage better

### ISSUE THREAD

**Issue by OR13** [w3c/cg-reports#4]
The README should include full instructions for submitting a FINAL CG report.

The instructions should be a list of actions to take, including guidance on using respec, with screenshots.

**Comment by OR13** [comment]
I will take a stab at this and once its approved, update the the final cg for lds-jws2020.

**Comment by OR13** [comment]
@dontcallmedom @iherman I can't assign myself this issue, but I intend to open a PR shortly.

**Comment by dontcallmedom** [comment]
closed by #6
